diamante_desk_bundle:
    resource:     "@DiamanteDeskBundle/Controller"
    type:         annotation
    prefix:       /desk

diamante_desk_api_branch:
    resource:     diamante.branch.api.service_diamante
    type:         diamante_rest_service
    prefix:       /api/diamante/rest/{version}/desk/
    requirements:
        version:  latest|v1
        _format:  xml|json
    defaults:
        version:  latest
        _format:  json

diamante_desk_api_branch_oro:
    resource:     diamante.branch.api.service_oro
    type:         diamante_rest_service
    prefix:       /api/rest/{version}/desk/
    requirements:
        version:  latest|v1
        _format:  xml|json
    defaults:
        version:  latest
        _format:  json

diamante_desk_api_ticket:
    resource:     diamante.ticket.api.service_diamante
    type:         diamante_rest_service
    prefix:       /api/diamante/rest/{version}/desk/
    requirements:
        version:  latest|v1
        _format:  xml|json
    defaults:
        version:  latest
        _format:  json

diamante_desk_api_ticket_oro:
    resource:     diamante.ticket.api.service_oro
    type:         diamante_rest_service
    prefix:       /api/rest/{version}/desk/
    requirements:
        version:  latest|v1
        _format:  xml|json
    defaults:
        version:  latest
        _format:  json

diamante_desk_api_comment:
    resource:     diamante.comment.api.service_diamante
    type:         diamante_rest_service
    prefix:       /api/diamante/rest/{version}/desk/
    requirements:
        version:  latest|v1
        _format:  xml|json
    defaults:
        version:  latest
        _format:  json

diamante_desk_api_comment_oro:
    resource:     diamante.comment.api.service_oro
    type:         diamante_rest_service
    prefix:       /api/rest/{version}/desk/
    requirements:
        version:  latest|v1
        _format:  xml|json
    defaults:
        version:  latest
        _format:  json

diamante_desk_api_watchers:
    resource:     diamante.watcher.service.api
    type:         diamante_rest_service
    prefix:       /api/diamante/rest/{version}/desk/
    requirements:
        version:  latest|v1
        _format:  xml|json
    defaults:
        version:  latest
        _format:  json
