Diamante\DeskBundle\Model\Ticket\Comment:
    accessor_order: alphabetical
    properties:
        ticket:
            exclude: true
        author:
            exclude: true
    virtual_properties:
        getTicketId:
            serialized_name: ticket
            type: integer
        getAuthorId:
            serialized_name: author
            type: integer
        getAuthorType:
            serialized_name: author_type
            type: string
